### ISSUE TITLE
multiEWS function not apply for multiple time series containing sparse values?

### ISSUE THREAD

**Issue by Huangmp1996** [duncanobrien/EWSmethods#5]
I try to calculate the EWS for a community comprising a time series of four species:
 ```{r,echo = FALSE}
library(EWSmethods)
data <- as.data.frame(cbind(
'year' = seq(1:19), 
'species_A' = c(5, 6, 7, 3, 5, 8, 21, 6, 2, 4, 5, 9, 8, 5, 6, 12, 5, 1, 12), 
'species_B' = c(5, 6, 9, 8, 1, 10, 3, 1, 5, 5, 2, 10, 5, 2, 2, 5, 9, 2, 5), 
'species_C' = c(0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0), 
'species_D' = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1)
)
)
multiEWS(data, method = "expanding",  threshold = 2, tail.direction = "one.tailed")
```

but I get the following error:

Error in svd(cov(x)) : infinite or missing values in 'x'

However, svd(cov(data[,-1])) is ok, and I also check the data according to https://stackoverflow.com/questions/21423375/r-svd-function-infinite-or-missing-values-in-x.

Deleting all columns containing 0 values works, but this will lose too much information.  How should I resolve this error?  I would greatly appreciate any guidance or tips you could offer.

**Comment by duncanobrien** [comment]
Thank your message.

Unfortunately, this is an unavoidable error given the sparsity of your data. The long run of zeroes in `speciesC` and `speciesD` prevents the singular value decomposition of the **windowed time series**, as NaNs are generated if the data is scaled. Remember you are only giving multiEWS a subset of your data at a time, because multivariate EWSs are estimated in an expanding or a rolling window.

In your repex, the error is returned because the covariance matrix generates NaNs. multiEWS is therefore not going to work for this specific dataset - or any dataset where a run of unchanging values occurs longer than the window size.

For example:
```
window <- 50
winsize <-  round(dim(data)[1] * window/100)

windowed_data <- lapply(1:(NROW(data)-winsize), function(i){
  data[i:(i+winsize),-1]
  })

x <- scale(windowed_data[[1]])
svd(cov(x)) #error because of NaN
```
Even if we allow sparse time series, then this generates downstream errors:
```
window <- 50
winsize <-  round(dim(data)[1] * window/100)

windowed_data_prescaled <- lapply(1:(NROW(data)-winsize), function(i){
  sapply(data[i:(i+winsize),-1],FUN = function(x){ifelse(length(unique(x)) == 1,return(x),return(c(scale(x))))} )
}) #don't scale if all values constant in the time series

svd <- svd(cov(windowed_data_prescaled[[1]]))
a <- svd$u%*%diag(svd$d^(-0.5))%*%t(svd$u)
y <- x%*%a #error because of Inf
```

 I would recommend either: 
1.  dropping the problematic species
2.  manually estimating the univariate EWS using uniEWS and then averaging across your species. 

I understand this is not the ideal outcome, but early warning signals are notoriously poor for short and sparse time series, with most empirical indicators tested on mathematical models with 100s-1000s of time points ( https://doi.org/10.1002/ece3.8123; https://doi.org/10.1101/2023.09.25.559298; https://doi.org/10.1098/rsta.2011.0304). This is obviously almost useless for most ecological datasets.

**Comment by Huangmp1996** [comment]
Thank you so much for your help!

**Comment by Huangmp1996** [comment]
Following your suggestions, I have decided to drop the problematic species. However, I am still uncertain about how to identify these problematic species and which criteria to use. Here are my thoughts:

For the "rolling" method in multiEWS:

1. The number of consecutive zeros should not exceed the window size.

For the "expanding" method in multiEWS:

1. The number of consecutive zeros should not exceed the burn-in period.
2. ...

Despite adhering to these criteria, I encountered an error after dropping the problematic species (see attached data: [example.csv](https://github.com/user-attachments/files/16154394/example.csv)):
```{r,eval=FALSE}
library(EWSmethods)
data <- read.csv('example.csv')  # data that dropped the problematic species
spp_exp_ews <- multiEWS(data = data, method = "expanding", metrics = 'pcaAR',
    threshold = 2, tail.direction = "one.tailed", burn_in = 5)
```
This resulted in the following error:
```{r,eval=FALSE}
Error in svd(cov.zd/(n - 1)): infinite or missing values in 'x'
Traceback:

1. multiEWS(data = data_species_preserved, method = "expanding", 
 .     metrics = "pcaAR", threshold = 2, tail.direction = "one.tailed", 
 .     burn_in = burn_in)
3. wMAF(data = data, metrics = metrics, threshold = threshold, burn_in = burn_in, 
 .     tail.direction = tail.direction, method = "expanding")
4. maf(x = data[1:i, -1])
5. svd(cov.zd/(n - 1))
6. stop("infinite or missing values in 'x'")
```
I have examined the data and suspect that the issue may stem from relatively low values in column H. Upon removing this column, the function works correctly:
```{r,eval=FALSE}
spp_exp_ews <- multiEWS(data = data[,-9], method = "expanding", metrics = 'pcaAR',
     threshold = 2, tail.direction = "one.tailed", burn_in = 5)  # works well
```
Therefore, is there a function or a clear standard available to define and drop problematic species?

**Comment by duncanobrien** [comment]
@Huangmp1996 I can't seem to find your email to reply to directly so I'm pinging you here.

I can't seem to reproduce your error using `example.csv`. I've attached the output below.


Just to clarify, it is not necessarily a period of consecutive **zeros** that causes errors, its is a **consecutive period of any unchanging values**. So `c(0.1,0.02,0.5,0.5,0.5,0.5,0.03)` may also generate errors if winsize/burn_in is too low.

```
data <- read.csv("example.csv")

spp_exp_ews1 <- EWSmethods::multiEWS(data = data, method = "expanding", metrics = 'pcaAR',
                        threshold = 2, tail.direction = "one.tailed", burn_in = 5)

plot(spp_exp_ews1)

spp_exp_ews2 <- EWSmethods::multiEWS(data = data, method = "rolling", metrics = 'pcaAR',
                       winsize = 50)

plot(spp_exp_ews2)
```
<img width="1236" alt="Screenshot 2024-07-10 at 09 37 08" src="https://github.com/duncanobrien/EWSmethods/assets/79991977/187be618-b156-4cd6-a1dd-851e07b64f1d">

<img width="1192" alt="Screenshot 2024-07-10 at 09 37 27" src="https://github.com/duncanobrien/EWSmethods/assets/79991977/310f7d73-46f9-427b-9088-8d15fd71b5b0">

**Comment by Huangmp1996** [comment]
Thank you so much for your reply. I have found that this error resulted from the specified values that can not apply for svd (here is the example data 
[example (1).csv](https://github.com/user-attachments/files/16158131/example.1.csv)
)

After I rounded the data, it works.

But I wonder is there a function or a clear standard available to define and drop problematic species?

**Comment by duncanobrien** [comment]
Unfortunately, there is no function or standard to define and drop problematic species. In my work, I use a checking step prior to running EWS analysis. It looks like below:

```
window <- round(dim(data)[1] * winsize / 100) #calculate the length of the window
spp_col <- names(data)[grepl("^species", names(data))] #list the species columns
 
ts_check <- sapply(
          spp_col, #for each species
          FUN = function(j) {
            length(unique(data[[j]])) == 1 | #identify whether all values are the same
              (sum(as.numeric(base::table(data[[j]]) %in% c(1, 2))) == 1 & 
                 length(unique(data[[j]])) == 2) | #or if all but one value is the same
              any(rle(data[[j]])$lengths >= (window)) #or if there is a run consecutive values larger than the window
          }
        )

data <- data[,!ts_check] #drop those problematic species
```
I also had a quick look at `data.1.csv`. I think the issue is a floating point error for that exact combination of data - you're unlucky. If you increase `burn_in` to 6, round by one digit, or multiply to a different magnitude, the function appears to work.

**Comment by Huangmp1996** [comment]
I see—many thanks for your kind help.
